# Generated by Django 4.2.2 on 2023-06-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cust_reg',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('district', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='emp_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
