# Generated by Django 4.2.2 on 2023-06-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0002_cust_reg_emp_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stationlist',
            fields=[
                ('station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stations', models.CharField(max_length=20)),
            ],
        ),
    ]
