# Generated by Django 4.2.2 on 2023-06-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0003_stationlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('Vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Vehiclename', models.CharField(max_length=20)),
            ],
        ),
    ]
