# Generated by Django 4.2.2 on 2023-06-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0004_vehicles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('trspt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('adrs', models.CharField(max_length=20)),
                ('station', models.CharField(max_length=20)),
                ('adhar', models.IntegerField()),
                ('driving', models.CharField(max_length=20)),
                ('vehicle', models.IntegerField()),
                ('model', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('regnum', models.IntegerField()),
                ('fon', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
