# Generated by Django 4.2.2 on 2023-06-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0005_transportation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='vehicle',
            field=models.CharField(max_length=20),
        ),
    ]
