# Generated by Django 4.2.2 on 2023-06-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0006_alter_transportation_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='stay',
            fields=[
                ('stay_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('dist', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('Phone', models.IntegerField()),
                ('desc', models.CharField(max_length=50)),
                ('File', models.FileField(upload_to='')),
            ],
        ),
    ]
