# Generated by Django 4.2.2 on 2023-06-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0010_addjobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobapply',
            fields=[
                ('job_Applied_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_id', models.IntegerField()),
                ('cus_id', models.IntegerField()),
            ],
        ),
    ]
