# Generated by Django 4.2.2 on 2023-06-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0012_alter_jobapply_cus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
