# Generated by Django 4.2.2 on 2023-06-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0013_jobapply_file_jobapply_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTicket',
            fields=[
                ('Ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cid', models.CharField(max_length=20)),
                ('fromsta', models.CharField(max_length=20)),
                ('tosta', models.CharField(max_length=20)),
                ('tickett', models.IntegerField()),
                ('total', models.IntegerField()),
                ('bdate', models.DateField()),
            ],
        ),
    ]
