# Generated by Django 4.2.2 on 2023-06-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0014_bookticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='Type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
