# Generated by Django 4.2.2 on 2023-06-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0015_vehicles_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='SeatingCapacity',
            field=models.CharField(default='', max_length=20),
        ),
    ]
