# Generated by Django 4.2.2 on 2023-06-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0016_transportation_seatingcapacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTransportations',
            fields=[
                ('bkid', models.IntegerField(primary_key=True, serialize=False)),
                ('cid', models.IntegerField()),
                ('taid', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
            ],
        ),
    ]
