# Generated by Django 4.2.2 on 2023-06-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0017_booktransportations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('Feedback_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cust_id', models.IntegerField()),
                ('fdate', models.DateField()),
                ('feedback', models.CharField(max_length=50)),
            ],
        ),
    ]
