# Generated by Django 4.2.1 on 2023-06-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0018_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllStation',
            fields=[
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle', models.CharField(max_length=20)),
            ],
        ),
    ]
