# Generated by Django 4.2.1 on 2023-06-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0019_allstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='capacity',
            field=models.CharField(max_length=20),
        ),
    ]
