# Generated by Django 4.1.3 on 2023-07-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0020_alter_transportation_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='regnum',
            field=models.CharField(max_length=20),
        ),
    ]
