# Generated by Django 4.2.2 on 2023-07-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0021_alter_transportation_regnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Updated_Date', models.DateField()),
                ('file', models.FileField(upload_to='project/file')),
            ],
        ),
    ]
