# Generated by Django 4.2.2 on 2023-07-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0022_timming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timming',
            name='file',
            field=models.FileField(upload_to='metrogenapp/file'),
        ),
    ]
