# Generated by Django 4.2.1 on 2023-09-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0023_alter_timming_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='Cust_email',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='Cust_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='Cust_phone',
            field=models.IntegerField(default=0),
        ),
    ]
