# Generated by Django 4.2.1 on 2023-09-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0024_jobapply_cust_email_jobapply_cust_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapply',
            name='position',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapply',
            name='ref',
            field=models.CharField(default='', max_length=20),
        ),
    ]
