# Generated by Django 4.2.1 on 2023-09-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0025_jobapply_position_jobapply_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapply',
            old_name='position',
            new_name='post',
        ),
    ]
