# Generated by Django 4.2.2 on 2023-10-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0026_rename_position_jobapply_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='AdhaarNumber',
            field=models.FileField(default='', upload_to='metrogenapp/media/Transportor'),
        ),
    ]
