# Generated by Django 4.2.2 on 2023-10-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0027_transportation_adhaarnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='CarPhoto',
            field=models.FileField(default='', upload_to='metrogenapp/media/Transportor'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='PersonalPhoto',
            field=models.FileField(default='', upload_to='metrogenapp/media/Transportor'),
        ),
    ]
