# Generated by Django 4.2.2 on 2023-10-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0028_transportation_carphoto_transportation_personalphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='IsActive',
            field=models.CharField(default='', max_length=20),
        ),
    ]
