# Generated by Django 4.2.2 on 2023-10-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0029_transportation_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='IsActive',
            field=models.CharField(default='False', max_length=20),
        ),
    ]
