# Generated by Django 4.2.2 on 2023-10-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrogenapp', '0030_alter_transportation_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjobs',
            name='vaccancy',
            field=models.IntegerField(default=0),
        ),
    ]
